name: Publish

on:
  workflow_dispatch:
    inputs:
      linter:
        description: 'Linter package to publish'
        required: true
        type: choice
        options:
          - eslint-plugin

permissions:
  contents: write
  packages: write

jobs:
  checks:
    name: Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Check user permissions
        uses: 74th/workflow-permission-action@1.0.0
        with:
          users: dedece35,glalloue,jhertout,jules-delecour-dav,olegoaer,zippy1978,utarwyn

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get package version
        id: package-version
        run: echo "version=$(cat ${{ inputs.linter }}/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Check tag non-existence
        run: if git show-ref --tags --verify --quiet -- "refs/tags/${{ inputs.linter }}/${{ steps.package-version.outputs.version }}"; then echo "::error::Tag already exists" && exit 1; fi

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: ${{ inputs.linter }}/CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.linter }} ${{ steps.package-version.outputs.version }}
          tag_name: ${{ inputs.linter }}/${{ steps.package-version.outputs.version }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Copy LICENSE
        run: cp LICENSE.md ${{ inputs.linter }}/

      - name: Publish package on NPM
        run: npm publish --access public --workspace ${{ inputs.linter }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Copy LICENSE
        run: cp LICENSE.md ${{ inputs.linter }}/

      - name: Add scope to package name
        run: npx --workspace ${{ inputs.linter }} --yes change-package-name @${{ github.repository_owner }}/ecocode-${{ inputs.linter }}

      - name: Configure GitHub Packages registry
        uses: bduff9/use-npmrc@v2.0.0
        with:
          dot-npmrc: |
            //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
            @${{ github.repository_owner }}:registry=https://npm.pkg.github.com
            always-auth=true
          working-directory: ${{ inputs.linter }}

      - name: Publish package on GitHub Packages
        run: npm publish --workspace ${{ inputs.linter }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
