name: Create release

on:
  workflow_dispatch:
    inputs:
      linter:
        description: 'Linter package to release'
        required: true
        type: choice
        options:
          - eslint-plugin

permissions:
  contents: write
  pull-requests: write

jobs:
  checks:
    name: Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Check user permissions
        uses: 74th/workflow-permission-action@1.0.0
        with:
          users: dedece35,glalloue,jhertout,jules-delecour-dav,olegoaer,zippy1978,utarwyn

  release:
    name: Create release Pull Request
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Apply version
        run: yarn version apply
        working-directory: ${{ inputs.linter }}

      - name: Get package version
        id: package-version
        run: echo "version=$(cat ${{ inputs.linter }}/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: ${{ inputs.linter }}/CHANGELOG.md
          prerelease: true

      - name: Update changelog
        uses: suyaser/keep-a-changelog-new-release@1.4.0
        with:
          version: ${{ steps.package-version.outputs.version }}
          tag: ${{ inputs.linter }}/${{ steps.package-version.outputs.version }}
          changelogPath: ${{ inputs.linter }}/CHANGELOG.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: release-${{ inputs.linter }}-${{ steps.package-version.outputs.version }}
          commit-message: Bump ${{ inputs.linter }} to ${{ steps.package-version.outputs.version }}
          title: Release ${{ inputs.linter }} v${{ steps.package-version.outputs.version }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          labels: release
          delete-branch: true
